

general_args: {
#  source: ../resources/traffic.mp4,
#  crop: {
#    top_y: 250,
#    bottom_y: none,
#    left_x: none,
#    right_x: 2800
#  },

#  source: ../resources/traffic2.mp4,
#  source: ../resources/hangzhou.mp4,
  source: ../resources/pedestrians.mp4,
#  source: ../resources/Highway-2.mp4,

  crop: {
    top_y: none,
    bottom_y: none,
    left_x: none,
    right_x: none
  },
  dest: demo.mp4,

  pre_trained: weights/yolo11s.pt,
  device: 0,  #  cpu or 0, 1, 2, 3...

  det_jam: false,
  det_queue: false,
  det_density: false,
  det_size: false,
  clas_color: false,
  det_section: false,
  det_velocity: false,
  det_volume: false,  # Volume of cars waiting for green light
  det_pim: true,  # Pedestrian Into Motor
  det_parking: false,  # Illegal parking
  det_wrongway: false,  # Driving wrong way
  det_lanechange: false,  # change lanes over solid line
  det_speeding: false,
}
jam_args: {
  n_threshold: 30,
  cls_indices: [ 2, 3, 5, 7 ]
}
queue_args: {
  #spacing_threshold: 30
  int_threshold: 0.75,  # intersection
  cls_indices: [ 2, 3, 5, 7 ],
  det_zone: [ [ 1171, 0 ], [ 434, 291 ], [ 596, 289 ], [ 1231, 0 ] ],
  lengths_m: [ 100, 3, 100, 3 ],
  angle: 90,
}
density_args: {
  int_threshold: 0.75,
  cls_indices: [ 2, 3, 5, 7 ],
  det_zone: [ [ 1171, 0 ], [ 434, 290 ], [ 596, 290 ], [ 1231, 0 ] ],
  length_m: 100
}
size_args: {
  cls_indices: [ 2, 5, 7 ],
  vertices: [ [ 0, 370 ], [ 1279, 370 ] ],
  thresholds: [ 160, 240 ],
  delta_second: 0.2
}
color_args: {
  cls_indices: [ 2, 5, 7 ],
  weights: weights/yolo11n-cls-color.pt,
  resize: [ 224, 224 ],
  min_size: [ 96, 96 ]
}
section_args: {
  cls_indices: [ 2, 3, 5, 7 ],
  det_line: [ [ 339, 215 ], [ 1060, 215 ] ],
  video_length: 10.0
}
velocity_args: {
  cls_indices: [ 2, 5, 7 ],
  det_zone: [ [ 567, 34 ], [ 109, 546 ], [ 1278, 546 ], [ 770, 34 ] ],
  lengths_m: [ 60, 20, 60, 20 ],
  angle: 90,
  delta_second: 0.4,
  video_length: 2.0
}
volume_args: {
  cls_indices: [ 2, 5, 7 ],
  det_zone: [ [ 500, 1180 ], [ 0, 1620 ], [ 0, 2159 ], [ 3600, 2159 ], [ 2660, 1126 ] ],
  iou_threshold: 0.6
}
pim_args: {
  cls_indices: [ 0, 3 ],
#  det_zone: [ [ 0, 144 ], [ 0, 663 ], [ 1919, 1049 ], [ 1919, 406 ] ],
  det_zone: [ [ 0, 0 ], [ 0, 144 ], [ 1919, 406 ], [ 1919, 0 ] ],
  iou_threshold: 0.6,
  duration_threshold: 5.0
}
plate_args: {
  det_model_dir: weights/ch_PP-OCRv4_det,
  rec_model_dir: weights/ch_PP-OCRv4_rec,
  cls_model_dir: weights/ch_ppocr_mobile_slim_v2.0_cls,
  use_angle_cls: false,
  lang: ch,
  show_log: false,
  use_gpu: true
}
parking_args: {
  cls_indices: [ 2, 5, 7 ],
  noparking_zone: [ [ 483, 230 ], [ 0, 637 ], [ 0, 719 ], [ 210, 719 ], [685, 230] ],
  delta_second: 0.4,
  duration_threshold: 10.0,
  video_length: 10.0,
  displacement_threshold: 16  # by px
}
wrongway_args: {
  cls_indices: [ 2, 5, 7],
  det_zone: [ [ 0, 34 ], [ 0, 546 ], [ 1278, 546 ], [ 770, 34 ] ],
  delta_second: 0.4,
  duration_threshold: 0.5,
  video_length: 2.0,
  correct_way: down
}
lanechange_args: {
  cls_indices: [ 2, 5, 7 ],
  det_zone: [ [ 567, 34 ], [ 109, 546 ], [ 1278, 546 ], [ 770, 34 ] ],
  delta_second: 0.3,
  duration_threshold: 0.5,
  video_length: 2.0,
  solid_lines: [
    [ [623, 0], [240, 719] ],
    [ [651, 0], [552, 719] ],
    [ [681, 0], [862, 719] ],
    [ [710, 0], [1160, 719] ],
  ]
}
speeding_args: {
  cls_indices: [ 2, 5, 7 ],
  det_zone: [ [ 567, 34 ], [ 109, 546 ], [ 1278, 546 ], [ 770, 34 ] ],
  lengths_m: [ 60, 20, 60, 20 ],
  angle: 90,
  delta_second: 0.4,
  duration_threshold: 1.0,
  video_length: 2.0,
  speed_threshold: 90  # km/h
}
