

general_args: {
#  source: ../resources/traffic.mp4,
#  crop: {
#    top_y: 250,
#    bottom_y: none,
#    left_x: none,
#    right_x: 2800
#  },

  source: ../resources/traffic2.mp4,
#  source: ../resources/hangzhou.mp4,
#  source: ../resources/pedestrians.mp4,
  crop: {
    top_y: none,
    bottom_y: none,
    left_x: none,
    right_x: none
  },
  dest: demo.mp4,

  pre_trained: weights/yolo11s.pt,
  device: 0,  #  cpu or 0, 1, 2, 3...

  det_jam: false,
  det_queue: false,
  det_density: false,
  det_size: true,
  clas_color: true,
  det_volume: true,
  det_speed: true,
  det_polume: false,  # Pedestrian volume
  det_pim: false,  # Pedestrian Into Motor
  det_parking: false,  # Illegal parking
  det_wrongway: true,  # Driving wrong way
  det_lanechange: true,  # change lanes over solid line
}
jam_args: {
  n_threshold: 30,
  cls_indices: [ 2, 3, 5, 7 ]
}
queue_args: {
  #spacing_threshold: 30
  int_threshold: 0.75,  # intersection
  cls_indices: [ 2, 3, 5, 7 ],
  det_zone: [ [ 1171, 0 ], [ 434, 291 ], [ 596, 289 ], [ 1231, 0 ] ],
  lengths_m: [ 100, 3, 100, 3 ],
  angle: 90,
}
density_args: {
  int_threshold: 0.75,
  cls_indices: [ 2, 3, 5, 7 ],
  det_zone: [ [ 1171, 0 ], [ 434, 290 ], [ 596, 290 ], [ 1231, 0 ] ],
  length_m: 100
}
size_args: {
  cls_indices: [ 2, 5, 7 ],
  vertices: [ [ 285, 354 ], [ 1088, 354 ] ],
  thresholds: [ 120, 180 ],
  delta_second: 0.2
}
color_args: {
  cls_indices: [ 2, 5, 7 ],
  weights: weights/yolo11n-cls-color.pt,
  resize: [ 224, 224 ],
  min_size: [ 96, 96 ]
}
volume_args: {
  cls_indices: [ 2, 3, 5, 7 ],
  det_zone: [ [ 567, 34 ], [ 109, 546 ], [ 1278, 546 ], [ 770, 34 ] ]
}
speed_args: {
  cls_indices: [ 2, 3, 5, 7 ],
  det_zone: [ [ 567, 34 ], [ 109, 546 ], [ 1278, 546 ], [ 770, 34 ] ],
  lengths_m: [ 60, 20, 60, 20 ],
  angle: 90,
  delta_second: 0.4
}
polume_args: {
  cls_indices: [ 0, 3 ],
  iou_threshold: 0.6
}
pim_args: {
  cls_indices: [ 0, 3 ],
  det_zone: [ [ 0, 144 ], [ 0, 663 ], [ 1920, 1049 ], [ 1920, 406 ] ],
  iou_threshold: 0.6
}
plate_args: {
  det_model_dir: weights/ch_PP-OCRv4_det,
  rec_model_dir: weights/ch_PP-OCRv4_rec,
  cls_model_dir: weights/ch_ppocr_mobile_slim_v2.0_cls,
  use_angle_cls: false,
  lang: ch,
  show_log: false,
  use_gpu: true
}
parking_args: {
  cls_indices: [ 2, 5, 7 ],
  det_zone: [ [ 483, 230 ], [ 0, 637 ], [ 0, 719 ], [ 210, 719 ], [685, 230] ],
  delta_second: 0.4,
  displacement_threshold: 16  # by px
}
wrongway_args: {
  cls_indices: [ 2, 5, 7],
  det_zone: [ [ 0, 34 ], [ 0, 546 ], [ 1278, 546 ], [ 770, 34 ] ],
  delta_second: 0.4,
  correct_way: up
}
lanechange_args: {
  cls_indices: [ 2, 5, 7 ],
  det_zone: [ [ 567, 34 ], [ 109, 546 ], [ 1278, 546 ], [ 770, 34 ] ],
  delta_second: 0.3,
  solid_lines: [
    [ [623, 0], [240, 719] ],
    [ [651, 0], [552, 719] ],
    [ [681, 0], [862, 719] ],
    [ [710, 0], [1160, 719] ],
  ]
}
