

general_args: {
#  source: ../resources/traffic.mp4,
#  crop: {
#    top_y: 250,
#    bottom_y: none,
#    left_x: none,
#    right_x: 2800
#  },
  source: ../resources/traffic2.mp4,
  crop: {
    top_y: none,
    bottom_y: none,
    left_x: none,
    right_x: none
  },
  device: 0,  #  cpu or 0, 1, 2, 3...

  det_jam: false,
  det_mip: false,  # Motor Into Pavement
  det_size: true,
  det_queue: false,
  det_density: false,
  det_volume: true,
  det_speed: true
}
jam_args: {
  n_threshold: 30,
  cls_indices: [ 2, 3, 5, 7 ]
}
mip_args: {  # Motor Into Pavement
}
size_args: {
  vertices: [ [ 535, 74 ], [ 810, 74 ] ]
}
queue_args: {
  #spacing_threshold: 30
  int_threshold: 0.75,  # intersection
  cls_indices: [ 2, 3, 5, 7 ],
  vertices: [ [ 1171, 0 ], [ 434, 291 ], [ 596, 289 ], [ 1231, 0 ] ],
  lengths_m: [ 100, 3, 100, 3 ],
  angle: 90,
}
density_args: {
  int_threshold: 0.75,
  cls_indices: [ 2, 3, 5, 7 ],
  vertices: [ [ 1171, 0 ], [ 434, 290 ], [ 596, 290 ], [ 1231, 0 ] ],
  length_m: 100
}
volume_args: {
  cls_indices: [ 2, 3, 5, 7 ],
  vertices: [ [ 567, 34 ], [ 109, 546 ], [ 1278, 546 ], [ 770, 34 ] ]
}
speed_args: {
  cls_indices: [ 2, 3, 5, 7 ],
  vertices: [ [ 567, 34 ], [ 109, 546 ], [ 1278, 546 ], [ 770, 34 ] ],
  lengths_m: [ 60, 20, 60, 20 ],
  angle: 90,
  grain_size_second: 0.4
}
