#0: beige
#1: black
#2: blue
#3: brown
#4: gold
#5: green
#6: grey
#7: orange
#8: pink
#9: purple
#10: red
#11: silver
#12: tan
#13: white
#14: yellow

0: black
1: blue
2: green
3: red
4: white
5: yellow
