log_dir: logs
auto_size: true
width: 1920
height: 1102
output_dir: runs
weight_dir: weights
video_dir: videos
cache_minutes: 60
det_width: 416
online: false
use_gpu: true
warmup: true
output_to_sql: false
output_to_obs: false
