main_window:
  window_icon: 'ui/assets/offline/AI-9.png'
  background_image: 'ui/assets/offline/bg.png'
  major_display_label_ss: 'background-color: grey; border-radius: 5px;'

title_bar:
  font_alimama_fangyuan_semibold: 'ui/assets/offline/AlimamaFangYuanTiVF-SemiBold.ttf'
  title_bar_ss: 'background-color: #1167FF;'
  title_bar_icon: 'ui/assets/offline/AI-9.png'
  text_label_ss: 'font-weight: normal; font-size: 30px; color: #FFFFFF; line-height: 36px; text-align: left; font-style: normal;'
  close_button_icon: 'ui/assets/offline/close.png'

task_detail:
  font_siyuan_cn_bold: 'ui/assets/offline/SourceHanSansCN-Bold.ttf'
  font_siyuan_cn_medium: 'ui/assets/offline/SourceHanSansCN-Medium.ttf'
  font_siyuan_cn_regular: 'ui/assets/offline/SourceHanSansCN-Regular.ttf'
  background_image: 'ui/assets/offline/box1.png'
  curr_task_icon: 'ui/assets/offline/ico-tit-renwu.png'
  curr_task_tag_label_ss: 'font-weight: bold; font-size: 20px; color: #333333; line-height: 30px; text-align: left; font-style: normal;'
  curr_task_line: 'ui/assets/offline/titline.png'
  ai_icon: 'ui/assets/offline/ico-ai.png'
  point_icon: 'ui/assets/offline/point.png'
  task_name_label_ss: 'font-weight: 500; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'
  camera_position_icon: 'ui/assets/offline/ico-sxt3d.png'
  camera_position_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
  camera_position_label_ss: 'font-weight: 400; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'
  video_source_icon: 'ui/assets/offline/ico-spy3d.png'
  video_source_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
  video_source_label_ss: 'font-weight: 400; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'
  point2_icon: 'ui/assets/offline/point.png'
  detection_tag_label_ss: 'font-weight: 500; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'
  detection_background_ss: 'border: 5px solid rgba(77,123,184,0.16);'
  detection_name_label_ss: 'font-weight: 400; font-size: 18px; color: #333333; line-height: 24px; text-align: left; font-style: normal;'
  start_time_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
  start_time_label_ss: 'font-weight: 400; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'
  end_time_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
  end_time_label_ss: 'font-weight: 400; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'
  dashed_line_ss: 'border: 1px dashed #A6B2C7;'
  creation_time_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
  creation_time_label_ss: 'font-weight: 400; font-size: 16px; color: #333333; line-height: 24px; text-align: left; font-style: normal;'

task_list:
  font_siyuan_cn_bold: 'ui/assets/offline/SourceHanSansCN-Bold.ttf'
  background_image: 'ui/assets/offline/box2.png'
  title_icon: 'ui/assets/offline/ico-tit-daizhixing.png'
  title_tag_label_ss: 'font-weight: bold; font-size: 20px; color: #333333; line-height: 30px; text-align: left; font-style: normal;'
  title_line: 'ui/assets/offline/titline.png'
  scroll_bar_ss: 'QScrollBar:vertical { background: transparent; width: 10px; margin: 0px 0px 0px 0px;} QScrollBar::handle:vertical { background: #BDC9DE; border-radius: 5px; border: 1px solid #93ABD5;}'
  scroll_item:
    font_siyuan_cn_medium: 'ui/assets/offline/SourceHanSansCN-Medium.ttf'
    font_siyuan_cn_regular: 'ui/assets/offline/SourceHanSansCN-Regular.ttf'
    scroll_item_icon: 'ui/assets/offline/ico-lukou.png'
    task_name_label_ss: 'font-weight: 500; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'
    start_time_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
    start_time_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
    dashed_line_ss: 'border: 1px dashed #90B3DE;'

major_display:
  font_siyuan_cn_regular: 'ui/assets/offline/SourceHanSansCN-Regular.ttf'
  background_image: 'ui/assets/offline/mid-pic.png'
  loading_icon: 'ui/assets/offline/loading.png'
  loading_tag_label_ss: 'font-weight: 400; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'

corpus_list:
  font_siyuan_cn_bold: 'ui/assets/offline/SourceHanSansCN-Bold.ttf'
  background_image: 'ui/assets/offline/box3.png'
  title_icon: 'ui/assets/offline/ico-tit-yiscyuliao.png'
  title_tag_label_ss: 'font-weight: bold; font-size: 20px; color: #333333; line-height: 30px; text-align: left; font-style: normal;'
  title_line: 'ui/assets/offline/titline2.png'
  scroll_bar_ss: 'QScrollBar:vertical { background: transparent; width: 10px; margin: 0px 0px 0px 0px;} QScrollBar::handle:vertical { background: #BDC9DE; border-radius: 5px; border: 1px solid #93ABD5;}'
  scroll_item:
    font_siyuan_cn_heavy: 'ui/assets/offline/SourceHanSansCN-Heavy.ttf'
    font_siyuan_cn_medium: 'ui/assets/offline/SourceHanSansCN-Medium.ttf'
    font_siyuan_cn_regular: 'ui/assets/offline/SourceHanSansCN-Regular.ttf'
    position_label_width_bias: 68
    model_label_width_bias: 0
    # unselected style below
    scroll_item_icon: 'ui/assets/offline/ico-yuliao(1).png'
    corpus_name_label_ss: 'font-weight: 500; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'
    position_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
    position_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
    model_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
    model_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
    start_time_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
    start_time_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
    end_time_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
    end_time_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
    dashed_line_ss: 'border: 1px dashed #90B3DE;'
    # selected style below
    vertical_line: 'ui/assets/offline/verline.png'
    scroll_item_selected_ss: 'background: #DCEBFF; box-shadow: 0px 1px 16px 0px rgba(15,245,255,0.5); border-radius: 4px; border: 1px solid #0FF5FF; opacity: 0.7; backdrop-filter: blur(9px);'
    scroll_item_selected_icon: 'ui/assets/offline/ico-yuliao-sel.png'
    corpus_name_selected_label_ss: 'font-weight: 800; font-size: 18px; color: #1474F4; line-height: 27px; text-align: left; font-style: normal;'
    position_tag_selected_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(45,118,247,0.7); line-height: 24px; text-align: left; font-style: normal;'
    position_selected_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(45,118,247,0.7); line-height: 24px; text-align: left; font-style: normal;'
    model_tag_selected_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(45,118,247,0.7); line-height: 24px; text-align: left; font-style: normal;'
    model_selected_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(45,118,247,0.7); line-height: 24px; text-align: left; font-style: normal;'
    start_time_selected_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(45,118,247,0.7); line-height: 24px; text-align: left; font-style: normal;'
    start_time_selected_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(45,118,247,0.7); line-height: 24px; text-align: left; font-style: normal;'
    end_time_selected_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(45,118,247,0.7); line-height: 24px; text-align: left; font-style: normal;'
    end_time_selected_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(45,118,247,0.7); line-height: 24px; text-align: left; font-style: normal;'

corpus_detail:
  font_siyuan_cn_heavy: 'ui/assets/offline/SourceHanSansCN-Heavy.ttf'
  font_siyuan_cn_bold: 'ui/assets/offline/SourceHanSansCN-Bold.ttf'
  font_siyuan_cn_regular: 'ui/assets/offline/SourceHanSansCN-Regular.ttf'
  background_image: 'ui/assets/offline/rectangle.png'
  corpus_name_background_ss: 'background: #DCEBFF; box-shadow: 0px 1px 16px 0px rgba(15,245,255,0.5); border-radius: 4px; border: 1px solid #0FF5FF; opacity: 0.7; backdrop-filter: blur(9px);'
  vertical_line_ss: 'background: #1474F4; border-radius: 3px;'
  corpus_name_icon: 'ui/assets/offline/ico-yuliao.png'
  corpus_name_label_ss: 'font-weight: 800; font-size: 18px; color: #1474F4; line-height: 27px; text-align: left; font-style: normal;'
  vertical_line: 'ui/assets/offline/verline2.png'
  info_title_tag_label_ss: 'font-weight: bold; font-size: 18px; color: #1474F4; line-height: 27px; text-align: left; font-style: normal;'
  model_icon: 'ui/assets/offline/ico-moxing.png'
  model_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
  model_label_ss: 'font-weight: 400; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'
  camera_id_icon: 'ui/assets/offline/ico-shexiangtou.png'
  camera_id_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
  camera_id_label_ss: 'font-weight: 400; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'
  video_type_icon: 'ui/assets/offline/ico-shipinleixing.png'
  video_type_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
  video_type_label_ss: 'font-weight: 400; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'
  video_source_icon: 'ui/assets/offline/ico-shipinyuan.png'
  video_source_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
  video_source_label_ss: 'font-weight: 400; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'
  start_time_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
  start_time_label_ss: 'font-weight: 400; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'
  end_time_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
  end_time_label_ss: 'font-weight: 400; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'
  dashed_line_ss: 'border: 1px dashed #96B6E0;'
  plate_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
  plate_label_ss: 'font-weight: 400; font-size: 16px; color: #333333; line-height: 24px; text-align: right; font-style: normal;'
  position_tag_label_ss: 'font-weight: 400; font-size: 16px; color: rgba(51,51,51,0.7); line-height: 24px; text-align: left; font-style: normal;'
  position_label_ss: 'font-weight: 400; font-size: 16px; color: #333333; line-height: 24px; text-align: right; font-style: normal;'
  vertical_line2: 'ui/assets/offline/verline2.png'
  display_title_tag_label_ss: 'font-weight: bold; font-size: 18px; color: #1474F4; line-height: 27px; text-align: left; font-style: normal;'
  display_background_image: 'ui/assets/offline/p-2.png'
  loading_icon: 'ui/assets/offline/loading.png'
  loading_tag_label_ss: 'font-weight: 400; font-size: 18px; color: #333333; line-height: 27px; text-align: left; font-style: normal;'

tray:
  tray_icon: 'ui/assets/offline/AI-9.png'

exit_dialog:
  font_pingfang_sc_bold: 'ui/assets/offline/PingFangSC-Bold.ttf'
  font_pingfang_sc_boldface: 'ui/assets/offline/PingFangSC-Boldface.ttf'
  font_pingfang_sc_regular: 'ui/assets/offline/PingFangSC-Regular.ttf'
  font_siyuan_cn_regular: 'ui/assets/offline/SourceHanSansCN-Regular.ttf'
  background_ss: 'background: #FFFFFF; border-radius: 4px;'
  title_tag_label_ss: 'font-weight: 600; font-size: 16px; color: #333333; line-height: 24px; text-align: left; font-style: normal;'
  close_button_icon: 'ui/assets/offline/close2.png'
  solid_line_ss: 'background: rgba(0,0,0,0.15);'
  middle_background_ss: 'background: #FAFAFA #FFFFFF; border-radius: 3px;'
  tip_icon: 'ui/assets/offline/tip.png'
  tip_tag_label_ss: 'font-weight: 400; font-size: 20px; color: #2D2F33; line-height: 30px; text-align: center; font-style: normal;'
  radio_button_unchecked_icon: 'ui/assets/offline/radio-unchecked.png'
  radio_button_checked_icon: 'ui/assets/offline/radio-checked.png'
  radio_button_ss: 'QRadioButton:unchecked { font-weight: 500; font-size: 16px; color: #606266; line-height: 22px; text-align: left; font-style: normal; text-transform: none;} QRadioButton:checked {font-weight: 500; font-size: 16px; color: #2D2F33; line-height: 22px; text-align: left; font-style: normal; text-transform: none;}'
  checkbox_unchecked_icon: 'ui/assets/offline/checkbox-unchecked.png'
  checkbox_checked_icon: 'ui/assets/offline/checkbox-checked.png'
  checkbox_ss: 'font-weight: 500; font-size: 16px; color: #606266; line-height: 22px; text-align: left; font-style: normal; text-transform: none;'
  cancel_button_ss: 'background: #FFFFFF; border-radius: 4px; border: 1px solid #CFD6E4; font-weight: 400; font-size: 16px; color: #2D2F33; line-height: 22px; text-align: center; font-style: normal;'
  ok_button_ss: 'background: #3770FF; border-radius: 4px; border: 1px solid #3770FF; font-weight: 400; font-size: 16px; color: #FFFFFF; line-height: 22px; text-align: center; font-style: normal;'
